#1
Yakov-Varnaev/BBQ-manager pull request #2
Opened 2022-08-18 18:57 UTC by max-bazarov

2022-08-18 19:06 UTC, Yakov-Varnaev requested changes

2022-08-19 09:55 UTC, Yakov-Varnaev requested changes

2022-08-19 09:55 UTC, Yakov-Varnaev commented on inventory/services.py
> +        for field in funcy.omit(self.instance._meta.fields, 'id'):
Does this work? Function omit works with mappings, not with sequences.

```
__class__.objects.create(**funcy.omit(kwargs, ['id']))
```

2022-08-19 09:55 UTC, Yakov-Varnaev commented on inventory/services.py
> +    def update(self, **kwargs: dict[str, type[Model]]) -> Model:
kwargs are kwargs, there is no need to annotate it. More than that we keys are not Model classes, but values of any type

2022-08-19 22:29 UTC, Yakov-Varnaev requested changes

2022-08-19 22:29 UTC, Yakov-Varnaev commented on inventory/tests.py
> +class TestMaterialArchiveService(TestCase, BaseArchiveServiceTests):
You can add this Base class to existing test.

2022-08-19 22:29 UTC, Yakov-Varnaev commented on core/tests.py
> +        assert self.instance.archived == True, (
Shouldn't we get instance from db rather than get it from test instance?

2022-08-19 22:29 UTC, Yakov-Varnaev commented on core/tests.py
> +
I'd like to see next asserts as well:

- [ ] amount of instances increased
- [ ] new instance has fields of old instance

2022-08-19 22:29 UTC, Yakov-Varnaev commented on inventory/services.py
>              if field.name not in kwargs:
If kwargs are empty we should raise exception, because it does not make sense to create same instance.

2022-08-20 10:21 UTC, max-bazarov commented on inventory/tests.py
> +class TestMaterialArchiveService(TestCase, BaseArchiveServiceTests):
Didn't get to which existing test

2022-08-20 10:42 UTC, max-bazarov commented on inventory/services.py
>              if field.name not in kwargs:
@Yakov-Varnaev Should I create custom exception?

2022-08-20 11:06 UTC, Yakov-Varnaev commented on inventory/services.py
>              if field.name not in kwargs:
This exception will be fine here
https://docs.djangoproject.com/en/4.1/ref/exceptions/#validationerror

2022-08-20 11:08 UTC, Yakov-Varnaev commented on inventory/tests.py
> +class TestMaterialArchiveService(TestCase, BaseArchiveServiceTests):
Rename `TestMaterialCreateService` to `TestMaterialService` and add BaseArchiveServiceTest there. Btw, rename `BaseArchiveServiceTest**s**` to `BaseArchiveServiceTest`

2022-08-20 12:31 UTC, Yakov-Varnaev requested changes

2022-08-20 12:31 UTC, Yakov-Varnaev commented on core/tests.py
> +        assert self.instance._meta.fields == new_instance._meta.fields, (
This always will be true. You should, check if all fields except for updated ones stay same.

E.g. we updated price. We should check that name of Material new instance is the same as old one.

2022-08-20 12:53 UTC, Yakov-Varnaev requested changes

2022-08-20 12:53 UTC, Yakov-Varnaev commented on core/tests.py
> +        old_fields = [field.name for field in self.instance._meta.fields]
```
unchanged_fields = [f.name for f in self.instance._meta.fields if f.name not in self.update_data]
assert all(getattr(self.instance, f) == getatter(new_instance, f) for f in unchanged_fields), (...)
```

2022-08-20 13:15 UTC, Yakov-Varnaev commented on core/tests.py
> +            f'is not equal to old instance data')
Not the proper way to close braces.

2022-08-20 13:18 UTC, Yakov-Varnaev commented on core/tests.py
> +        unchanged_fields = [f.name for f in self.instance._meta.f if f.name not in self.update_data]
`self.instance._meta.fields`*

2022-08-20 13:23 UTC, Yakov-Varnaev requested changes

2022-08-20 13:23 UTC, Yakov-Varnaev commented on core/services.py
> +        if not kwargs:
kwargs should be cleaned first.

2022-08-20 13:23 UTC, Yakov-Varnaev commented on core/services.py
> +        if not kwargs:
Omit all fields which are not model fields

2022-08-20 13:39 UTC, max-bazarov commented on core/services.py
> +        if not kwargs:
@Yakov-Varnaev how to validate kwargs

2022-08-20 13:54 UTC, Yakov-Varnaev commented on core/services.py
> +        if not kwargs:
```
kwargs = funcy.omit(kwargs, [f.name for f in self.instance._meta.fields])
```

2022-08-20 14:07 UTC, Yakov-Varnaev requested changes

2022-08-20 14:07 UTC, Yakov-Varnaev commented on core/services.py
> +            self.instance.archived = True
This line will never raise exception.
```
if not hasattr(self.instance, 'archived'):
     raise FieldDoesNotExist(...)
```

2022-08-20 14:08 UTC, max-bazarov commented on core/services.py
> +            self.instance.archived = True
@Yakov-Varnaev Why it will never raise exception?

2022-08-20 14:12 UTC, Yakov-Varnaev commented on core/services.py
> +            self.instance.archived = True
Because you will just add new attr to instance. Creation might raise an exception, but not assigning

2022-08-20 14:20 UTC, Yakov-Varnaev approved these changes

2022-08-20 14:21 UTC, merged