#5
Yakov-Varnaev/BBQ-manager pull request #43
Opened 2022-08-22 09:13 UTC by renrenovich

2022-08-22 10:33 UTC, Yakov-Varnaev requested changes

2022-08-22 10:33 UTC, Yakov-Varnaev commented on requirements.txt
> -asgiref==3.5.2
And why file is cleaned?

2022-08-22 11:08 UTC, max-bazarov requested changes

2022-08-22 11:08 UTC, max-bazarov commented on inventory/services.py
> +    def __init__(self, instance):
Try to copy Yakov's solution.
self.instance = instance
self.model = instance.__class__
etc.

2022-08-22 11:08 UTC, max-bazarov commented on inventory/tests.py
> +class TestMaterialDestroyService(APITestCase):
Inherit from BaseCRUDViewTest also

2022-08-22 12:19 UTC, Yakov-Varnaev requested changes

2022-08-22 12:19 UTC, Yakov-Varnaev commented on inventory/tests.py
> +class TestMaterialDestroyService(APITestCase):
Not BaseCRUDViewTest, but BaseCRUDArchiveViewTest.

2022-08-22 12:19 UTC, Yakov-Varnaev commented on employees/migrations/0001_employees_models.py
> +    ]
add new line in the end file to remove this file from pr.

2022-08-22 12:19 UTC, Yakov-Varnaev commented on inventory/serializers.py
> +    """Сериализатор для материала"""
Use English

2022-08-22 12:19 UTC, Yakov-Varnaev commented on inventory/services.py
> +        self.instance.delete()
You should return id of deleted instance.

2022-08-22 12:19 UTC, Yakov-Varnaev commented on inventory/tests.py
> +from rest_framework.test import APITestCase
use isort to fix imports

2022-08-22 12:19 UTC, Yakov-Varnaev commented on inventory/tests.py
> +    def SetUpClass(cls):
There is no such method. It's `setUpClass`.

2022-08-22 12:19 UTC, Yakov-Varnaev commented on inventory/tests.py
> +    def SetUpClass(cls):
And you should call super method too.

2022-08-22 12:19 UTC, Yakov-Varnaev commented on inventory/views.py
> +    def update(self, request, *args, **kwargs):
partial_update also should be redefined

2022-08-22 14:00 UTC, max-bazarov commented on inventory/serializers.py
> +    """Сериализатор для материала"""
@Yakov-Varnaev Is there any sense to leave such comments? This code is self-documented. Everybody understands that it is serializer for materials model

2022-08-22 14:18 UTC, Yakov-Varnaev commented on inventory/serializers.py
> +    """Сериализатор для материала"""
Agreed

2022-08-22 18:54 UTC, max-bazarov requested changes

2022-08-22 18:54 UTC, max-bazarov commented on inventory/tests.py
> +class TestMaterialDestroyService(APITestCase):
It would be better to rename this Test to TestMaterialDestroyViews and relocate testing destroy service to test above

2022-08-23 21:46 UTC, max-bazarov approved these changes

2022-08-23 21:46 UTC, Yakov-Varnaev approved these changes

2022-08-23 21:47 UTC, merged